# Generated by Django 4.0.4 on 2022-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_link', models.CharField(max_length=100)),
                ('news_date', models.DateField()),
                ('news_country', models.ManyToManyField(to='country.country')),
            ],
        ),
    ]
