# Generated by Django 4.0.4 on 2022-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={},
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
