# Generated by Django 4.0.4 on 2022-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('dni', models.CharField(default='0000000X', max_length=9, verbose_name='DNI')),
                ('phone_number', models.CharField(default='00000000', max_length=9, verbose_name='Phone Number')),
                ('postal_code', models.CharField(default='00000', max_length=5, verbose_name='Postal Code')),
            ],
        ),
    ]
