# Generated by Django 4.0.4 on 2022-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(default='calle xx', max_length=50, verbose_name='Adress'),
        ),
    ]
