# Generated by Django 4.0.4 on 2022-05-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_changed_my_article'),
        ('customer', '0002_changed_my_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='article_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_articles', to='article.article'),
            preserve_default=False,
        ),
    ]
