# Generated by Django 4.0.4 on 2022-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_article_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
    ]
