# Generated by Django 4.0.4 on 2022-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.CharField(default='djcesargarcia@gmail.com', max_length=50, verbose_name='email')),
                ('confirmation_password', models.CharField(default='12345', max_length=50, verbose_name='Confirmation Password')),
            ],
        ),
    ]
