# Generated by Django 4.0.4 on 2022-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
