# Generated by Django 4.0.4 on 2022-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default='djcesargarcia@gmail.com', max_length=50, verbose_name='email'),
        ),
    ]
