# Generated by Django 4.0.4 on 2022-04-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='confirmation_password',
            field=models.CharField(default='12345', max_length=50, verbose_name='Confirmation Password'),
        ),
    ]
