# Generated by Django 4.0.4 on 2022-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('origin', models.CharField(max_length=50, verbose_name='Origin')),
                ('destiny', models.CharField(max_length=50, verbose_name='Destiny')),
                ('postal_code', models.CharField(max_length=50, verbose_name='Postal Code')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
            ],
        ),
    ]
