# Generated by Django 4.0.4 on 2022-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLorry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('mma', models.FloatField(verbose_name='MMA')),
                ('tare', models.FloatField(verbose_name='Tare')),
                ('cuantity', models.FloatField(verbose_name='Cuantity')),
                ('empty_weight', models.FloatField(verbose_name='Empty Weight')),
                ('total_weight', models.FloatField(verbose_name='Total Weight')),
            ],
        ),
    ]
