# Generated by Django 4.0.4 on 2022-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadlorry', '0003_alter_loadlorry_cuantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadlorry',
            name='cuantity',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='empty_weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='mma',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='tare',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='total_weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loadlorry',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
