# Generated by Django 4.0.4 on 2022-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('weight', models.FloatField(max_length=5, verbose_name='Weight')),
                ('qrcode', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('price', models.FloatField(max_length=5, verbose_name='Price')),
            ],
        ),
    ]
