# Generated by Django 4.0.4 on 2022-04-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='qrcode',
            new_name='image',
        ),
    ]
