# Generated by Django 4.0.4 on 2022-04-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_changed_my_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.CharField(max_length=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.CharField(max_length=5, verbose_name='Weight'),
        ),
    ]
