# Generated by Django 4.0.4 on 2022-04-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_changed_my_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
