# Generated by Django 4.0.4 on 2022-05-13 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_changed_my_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('dni', models.CharField(max_length=9, verbose_name='Dni')),
                ('phone_number', models.CharField(max_length=9, verbose_name='Phone Number')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('article_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_provider', to='article.article')),
            ],
        ),
    ]
