# Generated by Django 4.0.4 on 2022-05-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicule',
            new_name='Vehicle',
        ),
    ]
