# Generated by Django 4.0.4 on 2022-05-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_driver_routes'),
        ('vehicle', '0002_rename_vehicule_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='driver.driver'),
            preserve_default=False,
        ),
    ]
