# Generated by Django 4.0.4 on 2022-05-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_driver_routes'),
        ('vehicle', '0003_changed_my_model_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='driver.driver', verbose_name='Driver'),
        ),
    ]
