# Generated by Django 4.0.4 on 2022-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('code_buy', models.IntegerField(max_length=5, verbose_name='Code Buy')),
                ('cuantity', models.IntegerField(max_length=5, verbose_name='Cuantity')),
                ('date_buy', models.DateField(auto_now=True)),
                ('date_out', models.DateField(auto_now=True)),
            ],
        ),
    ]
